export { default as Header } from "./Layout/Header"
export { default as Hero } from "./Hero"
export { default as Features } from "./Features"
export { default as Extensions } from "./Extensions"
export { default as FAQ } from "./FAQ"
